wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705694572.883509
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 35
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 35
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.8.10
      5: 0.16.2
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
